### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by oddbyte3d** [nmrugg/UE4Launcher#1]
Hi, First of all Great work... but the launcher doesn't do anything for me it loads to this window 
![Screenshot from 2020-02-09 20-34-48](https://user-images.githubusercontent.com/7324310/74102157-e0a21280-4b7b-11ea-9841-4bdaedcc7cab.png)
After that, it does nothing... Am I doing something wrong??

Cheers!

**Comment by nmrugg** [comment]
It doesn't yet <a href=https://github.com/EpicGames/UnrealEngine#linux>install UE4</a> for you. I'm working on that, but right now, you have to do it manually and then click the plus next to engine versions and tell it where it was installed.

If you do have it installed, then maybe the launcher is not looking for your projects in the right directory. I can make a way for the location to be configurable.

**Comment by oddbyte3d** [comment]
I have Unreal editor installed, projects are under "~/Unreal Projects "

Do you need any other info?

Cheers

**Comment by nmrugg** [comment]
I just pushed a change that I think will fix your issue.

Just run `git pull` to update, and see if it works now.

**Comment by oddbyte3d** [comment]
Awesome, well done. Works now.
Do you have a roadmap as to when other features may be available?

Cheers,
Scott

**Comment by nmrugg** [comment]
I don't have a roadmap yet. But it's a good idea. I'll think about it, and try to put one together.
