### ISSUE TITLE
Oddity when trying to log in

### ISSUE THREAD

**Issue by APoniatowski** [nmrugg/UE4Launcher#15]
Probably a minor bug, but when it comes to logging in, 

- the login page pops up on first run, but when closing the login window... it never pops up again, until I delete all the files and clone it again
- I tried logging in (only to discover that I forgot my password) and created an account, where it created the account, sent the 6 digit code and entered it and now I'm not logged in. and the login window is gone (won't pop up again)
- tried deleting the dir and start again after the successful account creation (window won't pop up again)
- I thought that maybe I need UE4 editor open, in order for it to work... nope, still no login window

These are my findings so far.

Also, I see that the project dir is using a default, instead of where one specified it in the editor (which is understandable why)

projectDirPaths: [
    '/home/$USER/Unreal Projects',
    '/home/$USER/Documents/Unreal Projects'
  ],

$  npm -v
6.14.7

OS: Manjaro Linux x86_64 
Kernel: 5.8.11-1-MANJARO 
Shell: bash 5.0.18 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 5.19.5

**Comment by APoniatowski** [comment]
update: it seems like it works, as I am logged in... but no indication that I am logged in (added some free assets from the free section and it showed up), just the terminal indicated to me that I am logged in

**Comment by oliiix** [comment]
omg thanks, now I could login after removing everything and redownloading it again! So yes I can confirm this problem with the login screen. Running on Ubuntu 20.10 latest.

Now as I could login I have to say this is amazing work!!! Exactly like the real launcher and everything is working, did recognize my UE Engines, adding an asset was no problem when i tried a second time into a newly created project (first time there was an error). THANK YOU SO MUCH!!!!
