### ISSUE TITLE
Asset Download 

### ISSUE THREAD

**Issue by Spiderfav** [nmrugg/UE4Launcher#8]
Any asset I try to download I keep getting the error message "Asset installation falied" . Yes it also has the typo. I have already added my engine path to it but no matter if I add it to engine or project, I still get the error message. I can also see that my projects have been added and I can launch the engine with no problem. Btw great work on this man! :+1:

**Comment by Spiderfav** [comment]
After some tweaking from the files, had to change filepath and then gave me correct error messages.

**Comment by etiennepinchon** [comment]
Hi I have the same issue, what do you mean by "tweaking files"? any specific steps? Thanks!

**Comment by Spiderfav** [comment]
Hi, it's cause it doesn't allow you to download assets from older versions of UE4 to the current one. It would be nice if there was any indication for it however.

**Comment by Ryder17z** [comment]
> Hi, it's cause it doesn't allow you to download assets from older versions of UE4 to the current one. It would be nice if there was any indication for it however.

how did you solve it? - because this is a pretty big issue.

**Comment by Spiderfav** [comment]
My solution is probably not best as it only fixes it temporarily, but since I knew all the assets I wanted to import, I downloaded the older version of UE4, imported the assets and then converted the project to the latest version.

**Comment by sknightq** [comment]
For me the solution is :
I found the project's version is always empty. so I add the version by hard code. As followings:
```
    projects.forEach(function (projectData)
    {
        items.push(new ContextualItem({
            label: projectData.name,
            onClick: function ()
            {
                projectData.version = "4.27" // hard code , you can change your version string
                addAssetToProject(assetData, projectData, assetContainerEl, assetImageEl);
            }
        }));
    });
```
